In [5]:
import numpy as np
x = np.arange(1,15)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
x[9]

10

In [10]:
x[-1]

14

In [11]:
y = x[2:10]=40
y

40

In [12]:
x

array([ 1,  2, 40, 40, 40, 40, 40, 40, 40, 40, 11, 12, 13, 14])

In [13]:
y= x.copy()
y

array([ 1,  2, 40, 40, 40, 40, 40, 40, 40, 40, 11, 12, 13, 14])