In [2]:
import numpy as np
x = np.arange(25).reshape(5,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [4]:
print(x[:,2:5:1])

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]


In [29]:
print(x[:,-1:-5:-1])

[[ 4  3  2  1]
 [ 9  8  7  6]
 [14 13 12 11]
 [19 18 17 16]
 [24 23 22 21]]


In [26]:
print(np.where(x>6,x<20,0))

[[0 0 0 0 0]
 [0 0 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 0 0 0]]


In [18]:
print(np.logical_and(x>6,x<22))

[[False False False False False]
 [False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True False False False]]


In [48]:
x[2][4]

14

In [49]:
x[2,4]

14

In [50]:
#slicing special part of the matrix
x[0:2,2:]

array([[2, 3, 4],
       [7, 8, 9]])

In [51]:
x[2:4,0:3]

array([[10, 11, 12],
       [15, 16, 17]])

In [62]:
y = np.arange(6,50)
y.sum()#to find sum of all elements in the list

1210

In [53]:
y > 20

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [54]:
y[y>20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [55]:
y[y%5==0]

array([10, 15, 20, 25, 30, 35, 40, 45])

In [56]:
a = np.arange(10)
b = np.arange(10,20)
print("a: \n",a)
print("b:\n",b)
c= a+b
print("addition is: ",c)

a: 
 [0 1 2 3 4 5 6 7 8 9]
b:
 [10 11 12 13 14 15 16 17 18 19]
addition is:  [10 12 14 16 18 20 22 24 26 28]


In [57]:
c = a/b
c

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [58]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [59]:
a = np.arange(12).reshape(3,4)
b= np.arange(12,24).reshape(3,4)
print("a is:  \n",a)
print("b is: \n",b)

a is:  
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b is: 
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [60]:
c = a+b
print("the addition is: \n",c)

the addition is: 
 [[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


In [61]:
c = a*b
print("the multiplication is: \n",c)

the multiplication is: 
 [[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]


In [32]:
import pyautogui as pt
import time
limit = input("enter: ")
messege = "thank you soo much Areeba\n"
i=0

while i<int(limit):
    pt.typewrite(messege)
    i+=1



ModuleNotFoundError: No module named 'pyautogui'