In [3]:
import numpy as np


In [8]:
np.arange(4,50)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [6]:
#range and reshape 
np.arange(50).reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [14]:
#linear space 1st perimeter for starting piont 2nd for upto and 3rd for number is specific range
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [18]:
x = [90,27,39,94,39,99]
x = np.array(x)
print(x.max())
print(x.min())

99
27


In [19]:
np.random.rand(5)

array([0.25563373, 0.07349397, 0.56791241, 0.07271832, 0.71577797])

In [20]:
np.random.randn(5)
#randn is for negative

array([-0.10427809, -0.01055927,  0.30684338, -2.15486081, -0.34268538])